### PR TITLE
thank you in js

### PR DESCRIPTION
**Pull request by jonasalmeida**
Thank you, NYTimes, for aggregating this data! 

I wrote a little js library to help others use your data resource. If you see fit merging it, I'll redirect the links at https://observablehq.com/@episphere/nytcovid19 directly to your rep.

best,

Jonas

### CODE REVIEW

**Comment by josh-byster** [comment]
This looks awesome! Thanks for publishing. If you'd like to include lat/long data for FIPS codes in addition, feel free to merge with [this](https://github.com/josh-byster/fips_lat_long/blob/master/fips_map.json) file I just published.

**Comment by jonasalmeida** [comment]
[done](https://github.com/episphere/covid-19-data/commit/58c2b358c545143c9d5c95c87413b59303ddcef1), thank you Josh! 
This is super-useful, I was wondering where I could get :-)

**Comment by albertsun** [comment]
Hi @jonasalmeida, thanks for the thought.

While I can see that being helpful to many people, we're going to keep this repo plain with just the data.

**Comment by jonasalmeida** [comment]
Off course Albert + this time you can't say the fed's wheren't helpful back ;-) :-D

**Pull request closed without merging**
