### PR TITLE
US state vaccination timeline

### PR DESCRIPTION
**Pull request by mgithub41**
Hi Team:

Adding US state vaccination timeline. Could you please review and merge.

### CODE REVIEW

**Comment by tiffehr** [comment]
Did you intend this for a fork of our repo?

**Comment by mgithub41** [comment]
Hi Tiff Fehr,

Wanted to add vaccination data to nytimes github repo. Seems like the pull
request was closed. Can you please let me know how to add vaccination data.

Thanks

**Comment by tiffehr** [comment]
@mgithub41 This dataset is provided by The New York Times staff, with a rigorous review process, documentation and automated update pipelines (for some datasets).  We are only offering data sets authored and validated by our process.  At the moment, we are actively collecting vaccination data from federal, state and health-department sources.  But we have not yet decided if we will include it here — there are currently many methodological ambiguities that must be resolved.

Thank you for offering your separate data set.  We appreciate the interest and understand the ongoing interest in vax data from our community around this repo.  I will add your PR in our Project-board Collection of additional data sets, if folks in the community wish to pull in your fork/PR.

**Comment by mgithub41** [comment]
Hi Tiff Fehr,

Thank you. Please let me know in case, if I could contribute in validating or collecting vaccine data. Currently collecting and processing it from https://covid.cdc.gov and other sources. Would be more than willing to contribute.

Thanks

**Comment by tiffehr** [comment]
Thank you for the offer -- I'll keep it in mind as our staffing changes.  We [have written about our data-acquisition effort](https://www.nytimes.com/2020/06/29/insider/coronavirus-cases-new-york-times.html), which might further clarify the scope of our operation and decisions about public data sources versus collecting our own.

**Pull request closed without merging**
