### PR TITLE
adding json versions of the data

### PR DESCRIPTION
**Pull request by copremesis**

### CODE REVIEW

**Comment by figital** [comment]
so which version of the data will now be the latest? which serializer/validator are you using?

**Comment by Cryowatt** [comment]
Instead of just adding the data you should include a script to generate new json data automatically.

Something like this:
`docker-compose.yml`
```yaml
version: '3'
services:
  json:
    image: mcr.microsoft.com/powershell
    volumes: 
      - ".:/nytimes/data:rw"
    entrypoint: [ "pwsh", "-WorkingDirectory", "/nytimes/data", "-EncodedCommand"]
    # Encoded command
    # $command = 'Get-ChildItem *.csv | % { Import-Csv $_ | ConvertTo-Json | Set-Content -Path "./$($_.BaseName).json" }'
    # [Convert]::ToBase64String([System.Text.Encoding]::Unicode.GetBytes($command))
    command: "RwBlAHQALQBDAGgAaQBsAGQASQB0AGUAbQAgACoALgBjAHMAdgAgAHwAIAAlACAAewAgAEkAbQBwAG8AcgB0AC0AQwBzAHYAIAAkAF8AIAB8ACAAQwBvAG4AdgBlAHIAdABUAG8ALQBKAHMAbwBuACAAfAAgAFMAZQB0AC0AQwBvAG4AdABlAG4AdAAgAC0AUABhAHQAaAAgACIALgAvACQAKAAkAF8ALgBCAGEAcwBlAE4AYQBtAGUAKQAuAGoAcwBvAG4AIgAgAH0A"
```

**Comment by albertsun** [comment]
@copremesis so that we don't have to maintain multiple data files, we are only going to be releasing this data in one format. Thank you for the thought though.

**Comment by mpaauw** [comment]
> 
> 
> Instead of just adding the data you should include a script to generate new json data automatically.
> 
> Something like this:
> `docker-compose.yml`
> 
> ```yaml
> version: '3'
> services:
>   json:
>     image: mcr.microsoft.com/powershell
>     volumes: 
>       - ".:/nytimes/data:rw"
>     entrypoint: [ "pwsh", "-WorkingDirectory", "/nytimes/data", "-EncodedCommand"]
>     # Encoded command
>     # $command = 'Get-ChildItem *.csv | % { Import-Csv $_ | ConvertTo-Json | Set-Content -Path "./$($_.BaseName).json" }'
>     # [Convert]::ToBase64String([System.Text.Encoding]::Unicode.GetBytes($command))
>     command: "RwBlAHQALQBDAGgAaQBsAGQASQB0AGUAbQAgACoALgBjAHMAdgAgAHwAIAAlACAAewAgAEkAbQBwAG8AcgB0AC0AQwBzAHYAIAAkAF8AIAB8ACAAQwBvAG4AdgBlAHIAdABUAG8ALQBKAHMAbwBuACAAfAAgAFMAZQB0AC0AQwBvAG4AdABlAG4AdAAgAC0AUABhAHQAaAAgACIALgAvACQAKAAkAF8ALgBCAGEAcwBlAE4AYQBtAGUAKQAuAGoAcwBvAG4AIgAgAH0A"
> ```

:why-are-you-like-this:

**Comment by rlahoda** [comment]
@copremesis If you are looking for json data, on my fork of this, I created a simple set of python scripts that parse the csv files into json data. https://github.com/rlahoda/covid-19-data 

I have the data converted to json on there as well but it may or may not stay current to the master set of data as I remember to merge theirs over

**Pull request closed without merging**
