### PR TITLE
Added example notebook

### PR DESCRIPTION
**Pull request by jsirott**
Simple jupyter notebook that demonstrates how to plot county data from the NYTimes county data for one example county (King County, WA).

### CODE REVIEW

**Comment by aaraney** [comment]
@jsirott I recreated your [notebook](https://colab.research.google.com/drive/1BOdX4sMI2P5_l2S077pIrJbEVDDpTE6E) in google colab so that it can be run online.

**Comment by coatsbj** [comment]
Thanks for this!

**Comment by albertsun** [comment]
Hi @jsirott, we're excited to see so many people jump in to do analysis!

But we are going to keep this repo plain with just the data for all users.

**Comment by jsirott** [comment]
Disappointed that the Times appears to be rejecting virtually all of the submitted pull requests. You might want to add info to the README to let folks know that you aren't accepting them.

**Pull request closed without merging**
