### PR TITLE
added gitattributes and lfsconfig

### PR DESCRIPTION
**Pull request by adamMolner**

### CODE REVIEW

**Comment by adamMolner** [comment]
looks good.

**Comment by tiffehr** [comment]
Perhaps this is on the wrong project?

**Comment by adamMolner** [comment]
I'm so embarrassed. I forked the repo but submitted the pull request on the wrong repo. Such an amateur mistake. Please forgive me. I knew this would come back to haunt me.

**Comment by tiffehr** [comment]
Not a problem!  I have done that myself, early in my git learning-curve and more recently as well.  It's not one of the more intuitive parts of git and forking, particularly from a busy GUI.

I saw you closed the issue but I wanted to make sure you had your work for your own fork before we did anything.

**Comment by adamMolner** [comment]
Thank you for understanding. Frankly, I should know better, but here we are. Anyway...I'm all good. everything is saved. Hopefully, we can all forget this ever happened. lol.

**Pull request closed without merging**
